#SB-23019 feat:Change all logs to follow the standard log format
project-sunbird/knowledge-mw-service pull request #241
Opened 2021-05-28 06:21 UTC by santoshilimi

2021-05-28 08:31 UTC, pallakartheekreddy requested changes

2021-05-28 08:31 UTC, pallakartheekreddy commented on src/service/questionService.js
> +  utilsService.logDebugInfo('question.list', req.rspObj, 'question list api called')
Change API name to `question-list`

2021-05-28 08:31 UTC, pallakartheekreddy commented on src/service/questionService.js
> +    utilsService.logErrorInfo('question.list', rspObj, 'Either identifier is missing or it is not list type')
same here

2021-09-16 12:54 UTC, keshavprasadms commented
Please open against 4.3.0 if required

2021-09-16 12:54 UTC, closed without merging